source 'https://rubygems.org/'

gem 'rails', '~> 5.1.4'
gem 'sqlite3'
gem 'mysql2'
gem 'puma', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.5'
gem 'haml-rails', '~> 0.9'
gem 'listen'
gem 'jquery-rails'
